# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\mycode\I2P2-TowerDefense

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\mycode\I2P2-TowerDefense\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\mycode\I2P2-TowerDefense\build\CMakeFiles C:\mycode\I2P2-TowerDefense\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\mycode\I2P2-TowerDefense\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 2024_I2P2_TowerDefense_with_answer

# Build rule for target.
2024_I2P2_TowerDefense_with_answer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 2024_I2P2_TowerDefense_with_answer
.PHONY : 2024_I2P2_TowerDefense_with_answer

# fast build rule for target.
2024_I2P2_TowerDefense_with_answer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/build
.PHONY : 2024_I2P2_TowerDefense_with_answer/fast

Bullet/AdvancedMissileBullet.obj: Bullet/AdvancedMissileBullet.cpp.obj
.PHONY : Bullet/AdvancedMissileBullet.obj

# target to build an object file
Bullet/AdvancedMissileBullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/AdvancedMissileBullet.cpp.obj
.PHONY : Bullet/AdvancedMissileBullet.cpp.obj

Bullet/AdvancedMissileBullet.i: Bullet/AdvancedMissileBullet.cpp.i
.PHONY : Bullet/AdvancedMissileBullet.i

# target to preprocess a source file
Bullet/AdvancedMissileBullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/AdvancedMissileBullet.cpp.i
.PHONY : Bullet/AdvancedMissileBullet.cpp.i

Bullet/AdvancedMissileBullet.s: Bullet/AdvancedMissileBullet.cpp.s
.PHONY : Bullet/AdvancedMissileBullet.s

# target to generate assembly for a file
Bullet/AdvancedMissileBullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/AdvancedMissileBullet.cpp.s
.PHONY : Bullet/AdvancedMissileBullet.cpp.s

Bullet/Bullet.obj: Bullet/Bullet.cpp.obj
.PHONY : Bullet/Bullet.obj

# target to build an object file
Bullet/Bullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/Bullet.cpp.obj
.PHONY : Bullet/Bullet.cpp.obj

Bullet/Bullet.i: Bullet/Bullet.cpp.i
.PHONY : Bullet/Bullet.i

# target to preprocess a source file
Bullet/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/Bullet.cpp.i
.PHONY : Bullet/Bullet.cpp.i

Bullet/Bullet.s: Bullet/Bullet.cpp.s
.PHONY : Bullet/Bullet.s

# target to generate assembly for a file
Bullet/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/Bullet.cpp.s
.PHONY : Bullet/Bullet.cpp.s

Bullet/FireBullet.obj: Bullet/FireBullet.cpp.obj
.PHONY : Bullet/FireBullet.obj

# target to build an object file
Bullet/FireBullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FireBullet.cpp.obj
.PHONY : Bullet/FireBullet.cpp.obj

Bullet/FireBullet.i: Bullet/FireBullet.cpp.i
.PHONY : Bullet/FireBullet.i

# target to preprocess a source file
Bullet/FireBullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FireBullet.cpp.i
.PHONY : Bullet/FireBullet.cpp.i

Bullet/FireBullet.s: Bullet/FireBullet.cpp.s
.PHONY : Bullet/FireBullet.s

# target to generate assembly for a file
Bullet/FireBullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FireBullet.cpp.s
.PHONY : Bullet/FireBullet.cpp.s

Bullet/FrostBullet.obj: Bullet/FrostBullet.cpp.obj
.PHONY : Bullet/FrostBullet.obj

# target to build an object file
Bullet/FrostBullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FrostBullet.cpp.obj
.PHONY : Bullet/FrostBullet.cpp.obj

Bullet/FrostBullet.i: Bullet/FrostBullet.cpp.i
.PHONY : Bullet/FrostBullet.i

# target to preprocess a source file
Bullet/FrostBullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FrostBullet.cpp.i
.PHONY : Bullet/FrostBullet.cpp.i

Bullet/FrostBullet.s: Bullet/FrostBullet.cpp.s
.PHONY : Bullet/FrostBullet.s

# target to generate assembly for a file
Bullet/FrostBullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/FrostBullet.cpp.s
.PHONY : Bullet/FrostBullet.cpp.s

Bullet/LaserBullet.obj: Bullet/LaserBullet.cpp.obj
.PHONY : Bullet/LaserBullet.obj

# target to build an object file
Bullet/LaserBullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/LaserBullet.cpp.obj
.PHONY : Bullet/LaserBullet.cpp.obj

Bullet/LaserBullet.i: Bullet/LaserBullet.cpp.i
.PHONY : Bullet/LaserBullet.i

# target to preprocess a source file
Bullet/LaserBullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/LaserBullet.cpp.i
.PHONY : Bullet/LaserBullet.cpp.i

Bullet/LaserBullet.s: Bullet/LaserBullet.cpp.s
.PHONY : Bullet/LaserBullet.s

# target to generate assembly for a file
Bullet/LaserBullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/LaserBullet.cpp.s
.PHONY : Bullet/LaserBullet.cpp.s

Bullet/MissileBullet.obj: Bullet/MissileBullet.cpp.obj
.PHONY : Bullet/MissileBullet.obj

# target to build an object file
Bullet/MissileBullet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/MissileBullet.cpp.obj
.PHONY : Bullet/MissileBullet.cpp.obj

Bullet/MissileBullet.i: Bullet/MissileBullet.cpp.i
.PHONY : Bullet/MissileBullet.i

# target to preprocess a source file
Bullet/MissileBullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/MissileBullet.cpp.i
.PHONY : Bullet/MissileBullet.cpp.i

Bullet/MissileBullet.s: Bullet/MissileBullet.cpp.s
.PHONY : Bullet/MissileBullet.s

# target to generate assembly for a file
Bullet/MissileBullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Bullet/MissileBullet.cpp.s
.PHONY : Bullet/MissileBullet.cpp.s

Enemy/AdvancedTankEnemy.obj: Enemy/AdvancedTankEnemy.cpp.obj
.PHONY : Enemy/AdvancedTankEnemy.obj

# target to build an object file
Enemy/AdvancedTankEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/AdvancedTankEnemy.cpp.obj
.PHONY : Enemy/AdvancedTankEnemy.cpp.obj

Enemy/AdvancedTankEnemy.i: Enemy/AdvancedTankEnemy.cpp.i
.PHONY : Enemy/AdvancedTankEnemy.i

# target to preprocess a source file
Enemy/AdvancedTankEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/AdvancedTankEnemy.cpp.i
.PHONY : Enemy/AdvancedTankEnemy.cpp.i

Enemy/AdvancedTankEnemy.s: Enemy/AdvancedTankEnemy.cpp.s
.PHONY : Enemy/AdvancedTankEnemy.s

# target to generate assembly for a file
Enemy/AdvancedTankEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/AdvancedTankEnemy.cpp.s
.PHONY : Enemy/AdvancedTankEnemy.cpp.s

Enemy/Enemy.obj: Enemy/Enemy.cpp.obj
.PHONY : Enemy/Enemy.obj

# target to build an object file
Enemy/Enemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/Enemy.cpp.obj
.PHONY : Enemy/Enemy.cpp.obj

Enemy/Enemy.i: Enemy/Enemy.cpp.i
.PHONY : Enemy/Enemy.i

# target to preprocess a source file
Enemy/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/Enemy.cpp.i
.PHONY : Enemy/Enemy.cpp.i

Enemy/Enemy.s: Enemy/Enemy.cpp.s
.PHONY : Enemy/Enemy.s

# target to generate assembly for a file
Enemy/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/Enemy.cpp.s
.PHONY : Enemy/Enemy.cpp.s

Enemy/PlaneEnemy.obj: Enemy/PlaneEnemy.cpp.obj
.PHONY : Enemy/PlaneEnemy.obj

# target to build an object file
Enemy/PlaneEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/PlaneEnemy.cpp.obj
.PHONY : Enemy/PlaneEnemy.cpp.obj

Enemy/PlaneEnemy.i: Enemy/PlaneEnemy.cpp.i
.PHONY : Enemy/PlaneEnemy.i

# target to preprocess a source file
Enemy/PlaneEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/PlaneEnemy.cpp.i
.PHONY : Enemy/PlaneEnemy.cpp.i

Enemy/PlaneEnemy.s: Enemy/PlaneEnemy.cpp.s
.PHONY : Enemy/PlaneEnemy.s

# target to generate assembly for a file
Enemy/PlaneEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/PlaneEnemy.cpp.s
.PHONY : Enemy/PlaneEnemy.cpp.s

Enemy/SoldierEnemy.obj: Enemy/SoldierEnemy.cpp.obj
.PHONY : Enemy/SoldierEnemy.obj

# target to build an object file
Enemy/SoldierEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/SoldierEnemy.cpp.obj
.PHONY : Enemy/SoldierEnemy.cpp.obj

Enemy/SoldierEnemy.i: Enemy/SoldierEnemy.cpp.i
.PHONY : Enemy/SoldierEnemy.i

# target to preprocess a source file
Enemy/SoldierEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/SoldierEnemy.cpp.i
.PHONY : Enemy/SoldierEnemy.cpp.i

Enemy/SoldierEnemy.s: Enemy/SoldierEnemy.cpp.s
.PHONY : Enemy/SoldierEnemy.s

# target to generate assembly for a file
Enemy/SoldierEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/SoldierEnemy.cpp.s
.PHONY : Enemy/SoldierEnemy.cpp.s

Enemy/TankEnemy.obj: Enemy/TankEnemy.cpp.obj
.PHONY : Enemy/TankEnemy.obj

# target to build an object file
Enemy/TankEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/TankEnemy.cpp.obj
.PHONY : Enemy/TankEnemy.cpp.obj

Enemy/TankEnemy.i: Enemy/TankEnemy.cpp.i
.PHONY : Enemy/TankEnemy.i

# target to preprocess a source file
Enemy/TankEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/TankEnemy.cpp.i
.PHONY : Enemy/TankEnemy.cpp.i

Enemy/TankEnemy.s: Enemy/TankEnemy.cpp.s
.PHONY : Enemy/TankEnemy.s

# target to generate assembly for a file
Enemy/TankEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Enemy/TankEnemy.cpp.s
.PHONY : Enemy/TankEnemy.cpp.s

Engine/Allegro5Exception.obj: Engine/Allegro5Exception.cpp.obj
.PHONY : Engine/Allegro5Exception.obj

# target to build an object file
Engine/Allegro5Exception.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Allegro5Exception.cpp.obj
.PHONY : Engine/Allegro5Exception.cpp.obj

Engine/Allegro5Exception.i: Engine/Allegro5Exception.cpp.i
.PHONY : Engine/Allegro5Exception.i

# target to preprocess a source file
Engine/Allegro5Exception.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Allegro5Exception.cpp.i
.PHONY : Engine/Allegro5Exception.cpp.i

Engine/Allegro5Exception.s: Engine/Allegro5Exception.cpp.s
.PHONY : Engine/Allegro5Exception.s

# target to generate assembly for a file
Engine/Allegro5Exception.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Allegro5Exception.cpp.s
.PHONY : Engine/Allegro5Exception.cpp.s

Engine/AudioHelper.obj: Engine/AudioHelper.cpp.obj
.PHONY : Engine/AudioHelper.obj

# target to build an object file
Engine/AudioHelper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/AudioHelper.cpp.obj
.PHONY : Engine/AudioHelper.cpp.obj

Engine/AudioHelper.i: Engine/AudioHelper.cpp.i
.PHONY : Engine/AudioHelper.i

# target to preprocess a source file
Engine/AudioHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/AudioHelper.cpp.i
.PHONY : Engine/AudioHelper.cpp.i

Engine/AudioHelper.s: Engine/AudioHelper.cpp.s
.PHONY : Engine/AudioHelper.s

# target to generate assembly for a file
Engine/AudioHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/AudioHelper.cpp.s
.PHONY : Engine/AudioHelper.cpp.s

Engine/Collider.obj: Engine/Collider.cpp.obj
.PHONY : Engine/Collider.obj

# target to build an object file
Engine/Collider.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Collider.cpp.obj
.PHONY : Engine/Collider.cpp.obj

Engine/Collider.i: Engine/Collider.cpp.i
.PHONY : Engine/Collider.i

# target to preprocess a source file
Engine/Collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Collider.cpp.i
.PHONY : Engine/Collider.cpp.i

Engine/Collider.s: Engine/Collider.cpp.s
.PHONY : Engine/Collider.s

# target to generate assembly for a file
Engine/Collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Collider.cpp.s
.PHONY : Engine/Collider.cpp.s

Engine/GameEngine.obj: Engine/GameEngine.cpp.obj
.PHONY : Engine/GameEngine.obj

# target to build an object file
Engine/GameEngine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/GameEngine.cpp.obj
.PHONY : Engine/GameEngine.cpp.obj

Engine/GameEngine.i: Engine/GameEngine.cpp.i
.PHONY : Engine/GameEngine.i

# target to preprocess a source file
Engine/GameEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/GameEngine.cpp.i
.PHONY : Engine/GameEngine.cpp.i

Engine/GameEngine.s: Engine/GameEngine.cpp.s
.PHONY : Engine/GameEngine.s

# target to generate assembly for a file
Engine/GameEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/GameEngine.cpp.s
.PHONY : Engine/GameEngine.cpp.s

Engine/Group.obj: Engine/Group.cpp.obj
.PHONY : Engine/Group.obj

# target to build an object file
Engine/Group.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Group.cpp.obj
.PHONY : Engine/Group.cpp.obj

Engine/Group.i: Engine/Group.cpp.i
.PHONY : Engine/Group.i

# target to preprocess a source file
Engine/Group.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Group.cpp.i
.PHONY : Engine/Group.cpp.i

Engine/Group.s: Engine/Group.cpp.s
.PHONY : Engine/Group.s

# target to generate assembly for a file
Engine/Group.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Group.cpp.s
.PHONY : Engine/Group.cpp.s

Engine/IControl.obj: Engine/IControl.cpp.obj
.PHONY : Engine/IControl.obj

# target to build an object file
Engine/IControl.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IControl.cpp.obj
.PHONY : Engine/IControl.cpp.obj

Engine/IControl.i: Engine/IControl.cpp.i
.PHONY : Engine/IControl.i

# target to preprocess a source file
Engine/IControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IControl.cpp.i
.PHONY : Engine/IControl.cpp.i

Engine/IControl.s: Engine/IControl.cpp.s
.PHONY : Engine/IControl.s

# target to generate assembly for a file
Engine/IControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IControl.cpp.s
.PHONY : Engine/IControl.cpp.s

Engine/IObject.obj: Engine/IObject.cpp.obj
.PHONY : Engine/IObject.obj

# target to build an object file
Engine/IObject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IObject.cpp.obj
.PHONY : Engine/IObject.cpp.obj

Engine/IObject.i: Engine/IObject.cpp.i
.PHONY : Engine/IObject.i

# target to preprocess a source file
Engine/IObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IObject.cpp.i
.PHONY : Engine/IObject.cpp.i

Engine/IObject.s: Engine/IObject.cpp.s
.PHONY : Engine/IObject.s

# target to generate assembly for a file
Engine/IObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IObject.cpp.s
.PHONY : Engine/IObject.cpp.s

Engine/IScene.obj: Engine/IScene.cpp.obj
.PHONY : Engine/IScene.obj

# target to build an object file
Engine/IScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IScene.cpp.obj
.PHONY : Engine/IScene.cpp.obj

Engine/IScene.i: Engine/IScene.cpp.i
.PHONY : Engine/IScene.i

# target to preprocess a source file
Engine/IScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IScene.cpp.i
.PHONY : Engine/IScene.cpp.i

Engine/IScene.s: Engine/IScene.cpp.s
.PHONY : Engine/IScene.s

# target to generate assembly for a file
Engine/IScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/IScene.cpp.s
.PHONY : Engine/IScene.cpp.s

Engine/LOG.obj: Engine/LOG.cpp.obj
.PHONY : Engine/LOG.obj

# target to build an object file
Engine/LOG.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/LOG.cpp.obj
.PHONY : Engine/LOG.cpp.obj

Engine/LOG.i: Engine/LOG.cpp.i
.PHONY : Engine/LOG.i

# target to preprocess a source file
Engine/LOG.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/LOG.cpp.i
.PHONY : Engine/LOG.cpp.i

Engine/LOG.s: Engine/LOG.cpp.s
.PHONY : Engine/LOG.s

# target to generate assembly for a file
Engine/LOG.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/LOG.cpp.s
.PHONY : Engine/LOG.cpp.s

Engine/Point.obj: Engine/Point.cpp.obj
.PHONY : Engine/Point.obj

# target to build an object file
Engine/Point.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Point.cpp.obj
.PHONY : Engine/Point.cpp.obj

Engine/Point.i: Engine/Point.cpp.i
.PHONY : Engine/Point.i

# target to preprocess a source file
Engine/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Point.cpp.i
.PHONY : Engine/Point.cpp.i

Engine/Point.s: Engine/Point.cpp.s
.PHONY : Engine/Point.s

# target to generate assembly for a file
Engine/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Point.cpp.s
.PHONY : Engine/Point.cpp.s

Engine/Resources.obj: Engine/Resources.cpp.obj
.PHONY : Engine/Resources.obj

# target to build an object file
Engine/Resources.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Resources.cpp.obj
.PHONY : Engine/Resources.cpp.obj

Engine/Resources.i: Engine/Resources.cpp.i
.PHONY : Engine/Resources.i

# target to preprocess a source file
Engine/Resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Resources.cpp.i
.PHONY : Engine/Resources.cpp.i

Engine/Resources.s: Engine/Resources.cpp.s
.PHONY : Engine/Resources.s

# target to generate assembly for a file
Engine/Resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Resources.cpp.s
.PHONY : Engine/Resources.cpp.s

Engine/Sprite.obj: Engine/Sprite.cpp.obj
.PHONY : Engine/Sprite.obj

# target to build an object file
Engine/Sprite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Sprite.cpp.obj
.PHONY : Engine/Sprite.cpp.obj

Engine/Sprite.i: Engine/Sprite.cpp.i
.PHONY : Engine/Sprite.i

# target to preprocess a source file
Engine/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Sprite.cpp.i
.PHONY : Engine/Sprite.cpp.i

Engine/Sprite.s: Engine/Sprite.cpp.s
.PHONY : Engine/Sprite.s

# target to generate assembly for a file
Engine/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Engine/Sprite.cpp.s
.PHONY : Engine/Sprite.cpp.s

Scene/BlackPlayScene.obj: Scene/BlackPlayScene.cpp.obj
.PHONY : Scene/BlackPlayScene.obj

# target to build an object file
Scene/BlackPlayScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/BlackPlayScene.cpp.obj
.PHONY : Scene/BlackPlayScene.cpp.obj

Scene/BlackPlayScene.i: Scene/BlackPlayScene.cpp.i
.PHONY : Scene/BlackPlayScene.i

# target to preprocess a source file
Scene/BlackPlayScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/BlackPlayScene.cpp.i
.PHONY : Scene/BlackPlayScene.cpp.i

Scene/BlackPlayScene.s: Scene/BlackPlayScene.cpp.s
.PHONY : Scene/BlackPlayScene.s

# target to generate assembly for a file
Scene/BlackPlayScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/BlackPlayScene.cpp.s
.PHONY : Scene/BlackPlayScene.cpp.s

Scene/DataGeneratingScene.obj: Scene/DataGeneratingScene.cpp.obj
.PHONY : Scene/DataGeneratingScene.obj

# target to build an object file
Scene/DataGeneratingScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DataGeneratingScene.cpp.obj
.PHONY : Scene/DataGeneratingScene.cpp.obj

Scene/DataGeneratingScene.i: Scene/DataGeneratingScene.cpp.i
.PHONY : Scene/DataGeneratingScene.i

# target to preprocess a source file
Scene/DataGeneratingScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DataGeneratingScene.cpp.i
.PHONY : Scene/DataGeneratingScene.cpp.i

Scene/DataGeneratingScene.s: Scene/DataGeneratingScene.cpp.s
.PHONY : Scene/DataGeneratingScene.s

# target to generate assembly for a file
Scene/DataGeneratingScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DataGeneratingScene.cpp.s
.PHONY : Scene/DataGeneratingScene.cpp.s

Scene/DifficultySelectScene.obj: Scene/DifficultySelectScene.cpp.obj
.PHONY : Scene/DifficultySelectScene.obj

# target to build an object file
Scene/DifficultySelectScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DifficultySelectScene.cpp.obj
.PHONY : Scene/DifficultySelectScene.cpp.obj

Scene/DifficultySelectScene.i: Scene/DifficultySelectScene.cpp.i
.PHONY : Scene/DifficultySelectScene.i

# target to preprocess a source file
Scene/DifficultySelectScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DifficultySelectScene.cpp.i
.PHONY : Scene/DifficultySelectScene.cpp.i

Scene/DifficultySelectScene.s: Scene/DifficultySelectScene.cpp.s
.PHONY : Scene/DifficultySelectScene.s

# target to generate assembly for a file
Scene/DifficultySelectScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/DifficultySelectScene.cpp.s
.PHONY : Scene/DifficultySelectScene.cpp.s

Scene/LoseScene.obj: Scene/LoseScene.cpp.obj
.PHONY : Scene/LoseScene.obj

# target to build an object file
Scene/LoseScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/LoseScene.cpp.obj
.PHONY : Scene/LoseScene.cpp.obj

Scene/LoseScene.i: Scene/LoseScene.cpp.i
.PHONY : Scene/LoseScene.i

# target to preprocess a source file
Scene/LoseScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/LoseScene.cpp.i
.PHONY : Scene/LoseScene.cpp.i

Scene/LoseScene.s: Scene/LoseScene.cpp.s
.PHONY : Scene/LoseScene.s

# target to generate assembly for a file
Scene/LoseScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/LoseScene.cpp.s
.PHONY : Scene/LoseScene.cpp.s

Scene/MapCreateScene.obj: Scene/MapCreateScene.cpp.obj
.PHONY : Scene/MapCreateScene.obj

# target to build an object file
Scene/MapCreateScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/MapCreateScene.cpp.obj
.PHONY : Scene/MapCreateScene.cpp.obj

Scene/MapCreateScene.i: Scene/MapCreateScene.cpp.i
.PHONY : Scene/MapCreateScene.i

# target to preprocess a source file
Scene/MapCreateScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/MapCreateScene.cpp.i
.PHONY : Scene/MapCreateScene.cpp.i

Scene/MapCreateScene.s: Scene/MapCreateScene.cpp.s
.PHONY : Scene/MapCreateScene.s

# target to generate assembly for a file
Scene/MapCreateScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/MapCreateScene.cpp.s
.PHONY : Scene/MapCreateScene.cpp.s

Scene/ModeSelectScene.obj: Scene/ModeSelectScene.cpp.obj
.PHONY : Scene/ModeSelectScene.obj

# target to build an object file
Scene/ModeSelectScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ModeSelectScene.cpp.obj
.PHONY : Scene/ModeSelectScene.cpp.obj

Scene/ModeSelectScene.i: Scene/ModeSelectScene.cpp.i
.PHONY : Scene/ModeSelectScene.i

# target to preprocess a source file
Scene/ModeSelectScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ModeSelectScene.cpp.i
.PHONY : Scene/ModeSelectScene.cpp.i

Scene/ModeSelectScene.s: Scene/ModeSelectScene.cpp.s
.PHONY : Scene/ModeSelectScene.s

# target to generate assembly for a file
Scene/ModeSelectScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ModeSelectScene.cpp.s
.PHONY : Scene/ModeSelectScene.cpp.s

Scene/NormalPlayScene.obj: Scene/NormalPlayScene.cpp.obj
.PHONY : Scene/NormalPlayScene.obj

# target to build an object file
Scene/NormalPlayScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/NormalPlayScene.cpp.obj
.PHONY : Scene/NormalPlayScene.cpp.obj

Scene/NormalPlayScene.i: Scene/NormalPlayScene.cpp.i
.PHONY : Scene/NormalPlayScene.i

# target to preprocess a source file
Scene/NormalPlayScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/NormalPlayScene.cpp.i
.PHONY : Scene/NormalPlayScene.cpp.i

Scene/NormalPlayScene.s: Scene/NormalPlayScene.cpp.s
.PHONY : Scene/NormalPlayScene.s

# target to generate assembly for a file
Scene/NormalPlayScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/NormalPlayScene.cpp.s
.PHONY : Scene/NormalPlayScene.cpp.s

Scene/PlayScene.obj: Scene/PlayScene.cpp.obj
.PHONY : Scene/PlayScene.obj

# target to build an object file
Scene/PlayScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/PlayScene.cpp.obj
.PHONY : Scene/PlayScene.cpp.obj

Scene/PlayScene.i: Scene/PlayScene.cpp.i
.PHONY : Scene/PlayScene.i

# target to preprocess a source file
Scene/PlayScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/PlayScene.cpp.i
.PHONY : Scene/PlayScene.cpp.i

Scene/PlayScene.s: Scene/PlayScene.cpp.s
.PHONY : Scene/PlayScene.s

# target to generate assembly for a file
Scene/PlayScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/PlayScene.cpp.s
.PHONY : Scene/PlayScene.cpp.s

Scene/ReversePlayScene.obj: Scene/ReversePlayScene.cpp.obj
.PHONY : Scene/ReversePlayScene.obj

# target to build an object file
Scene/ReversePlayScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReversePlayScene.cpp.obj
.PHONY : Scene/ReversePlayScene.cpp.obj

Scene/ReversePlayScene.i: Scene/ReversePlayScene.cpp.i
.PHONY : Scene/ReversePlayScene.i

# target to preprocess a source file
Scene/ReversePlayScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReversePlayScene.cpp.i
.PHONY : Scene/ReversePlayScene.cpp.i

Scene/ReversePlayScene.s: Scene/ReversePlayScene.cpp.s
.PHONY : Scene/ReversePlayScene.s

# target to generate assembly for a file
Scene/ReversePlayScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReversePlayScene.cpp.s
.PHONY : Scene/ReversePlayScene.cpp.s

Scene/ReviveScene.obj: Scene/ReviveScene.cpp.obj
.PHONY : Scene/ReviveScene.obj

# target to build an object file
Scene/ReviveScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReviveScene.cpp.obj
.PHONY : Scene/ReviveScene.cpp.obj

Scene/ReviveScene.i: Scene/ReviveScene.cpp.i
.PHONY : Scene/ReviveScene.i

# target to preprocess a source file
Scene/ReviveScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReviveScene.cpp.i
.PHONY : Scene/ReviveScene.cpp.i

Scene/ReviveScene.s: Scene/ReviveScene.cpp.s
.PHONY : Scene/ReviveScene.s

# target to generate assembly for a file
Scene/ReviveScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ReviveScene.cpp.s
.PHONY : Scene/ReviveScene.cpp.s

Scene/ScoreboardScene.obj: Scene/ScoreboardScene.cpp.obj
.PHONY : Scene/ScoreboardScene.obj

# target to build an object file
Scene/ScoreboardScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ScoreboardScene.cpp.obj
.PHONY : Scene/ScoreboardScene.cpp.obj

Scene/ScoreboardScene.i: Scene/ScoreboardScene.cpp.i
.PHONY : Scene/ScoreboardScene.i

# target to preprocess a source file
Scene/ScoreboardScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ScoreboardScene.cpp.i
.PHONY : Scene/ScoreboardScene.cpp.i

Scene/ScoreboardScene.s: Scene/ScoreboardScene.cpp.s
.PHONY : Scene/ScoreboardScene.s

# target to generate assembly for a file
Scene/ScoreboardScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/ScoreboardScene.cpp.s
.PHONY : Scene/ScoreboardScene.cpp.s

Scene/SettingsScene.obj: Scene/SettingsScene.cpp.obj
.PHONY : Scene/SettingsScene.obj

# target to build an object file
Scene/SettingsScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SettingsScene.cpp.obj
.PHONY : Scene/SettingsScene.cpp.obj

Scene/SettingsScene.i: Scene/SettingsScene.cpp.i
.PHONY : Scene/SettingsScene.i

# target to preprocess a source file
Scene/SettingsScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SettingsScene.cpp.i
.PHONY : Scene/SettingsScene.cpp.i

Scene/SettingsScene.s: Scene/SettingsScene.cpp.s
.PHONY : Scene/SettingsScene.s

# target to generate assembly for a file
Scene/SettingsScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SettingsScene.cpp.s
.PHONY : Scene/SettingsScene.cpp.s

Scene/StageSelectHandWriteScene.obj: Scene/StageSelectHandWriteScene.cpp.obj
.PHONY : Scene/StageSelectHandWriteScene.obj

# target to build an object file
Scene/StageSelectHandWriteScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectHandWriteScene.cpp.obj
.PHONY : Scene/StageSelectHandWriteScene.cpp.obj

Scene/StageSelectHandWriteScene.i: Scene/StageSelectHandWriteScene.cpp.i
.PHONY : Scene/StageSelectHandWriteScene.i

# target to preprocess a source file
Scene/StageSelectHandWriteScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectHandWriteScene.cpp.i
.PHONY : Scene/StageSelectHandWriteScene.cpp.i

Scene/StageSelectHandWriteScene.s: Scene/StageSelectHandWriteScene.cpp.s
.PHONY : Scene/StageSelectHandWriteScene.s

# target to generate assembly for a file
Scene/StageSelectHandWriteScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectHandWriteScene.cpp.s
.PHONY : Scene/StageSelectHandWriteScene.cpp.s

Scene/StageSelectScene.obj: Scene/StageSelectScene.cpp.obj
.PHONY : Scene/StageSelectScene.obj

# target to build an object file
Scene/StageSelectScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectScene.cpp.obj
.PHONY : Scene/StageSelectScene.cpp.obj

Scene/StageSelectScene.i: Scene/StageSelectScene.cpp.i
.PHONY : Scene/StageSelectScene.i

# target to preprocess a source file
Scene/StageSelectScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectScene.cpp.i
.PHONY : Scene/StageSelectScene.cpp.i

Scene/StageSelectScene.s: Scene/StageSelectScene.cpp.s
.PHONY : Scene/StageSelectScene.s

# target to generate assembly for a file
Scene/StageSelectScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StageSelectScene.cpp.s
.PHONY : Scene/StageSelectScene.cpp.s

Scene/StartScene.obj: Scene/StartScene.cpp.obj
.PHONY : Scene/StartScene.obj

# target to build an object file
Scene/StartScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StartScene.cpp.obj
.PHONY : Scene/StartScene.cpp.obj

Scene/StartScene.i: Scene/StartScene.cpp.i
.PHONY : Scene/StartScene.i

# target to preprocess a source file
Scene/StartScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StartScene.cpp.i
.PHONY : Scene/StartScene.cpp.i

Scene/StartScene.s: Scene/StartScene.cpp.s
.PHONY : Scene/StartScene.s

# target to generate assembly for a file
Scene/StartScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/StartScene.cpp.s
.PHONY : Scene/StartScene.cpp.s

Scene/SurvivalPlayScene.obj: Scene/SurvivalPlayScene.cpp.obj
.PHONY : Scene/SurvivalPlayScene.obj

# target to build an object file
Scene/SurvivalPlayScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SurvivalPlayScene.cpp.obj
.PHONY : Scene/SurvivalPlayScene.cpp.obj

Scene/SurvivalPlayScene.i: Scene/SurvivalPlayScene.cpp.i
.PHONY : Scene/SurvivalPlayScene.i

# target to preprocess a source file
Scene/SurvivalPlayScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SurvivalPlayScene.cpp.i
.PHONY : Scene/SurvivalPlayScene.cpp.i

Scene/SurvivalPlayScene.s: Scene/SurvivalPlayScene.cpp.s
.PHONY : Scene/SurvivalPlayScene.s

# target to generate assembly for a file
Scene/SurvivalPlayScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/SurvivalPlayScene.cpp.s
.PHONY : Scene/SurvivalPlayScene.cpp.s

Scene/WinScene.obj: Scene/WinScene.cpp.obj
.PHONY : Scene/WinScene.obj

# target to build an object file
Scene/WinScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/WinScene.cpp.obj
.PHONY : Scene/WinScene.cpp.obj

Scene/WinScene.i: Scene/WinScene.cpp.i
.PHONY : Scene/WinScene.i

# target to preprocess a source file
Scene/WinScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/WinScene.cpp.i
.PHONY : Scene/WinScene.cpp.i

Scene/WinScene.s: Scene/WinScene.cpp.s
.PHONY : Scene/WinScene.s

# target to generate assembly for a file
Scene/WinScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Scene/WinScene.cpp.s
.PHONY : Scene/WinScene.cpp.s

Turret/AdvancedMissileTurret.obj: Turret/AdvancedMissileTurret.cpp.obj
.PHONY : Turret/AdvancedMissileTurret.obj

# target to build an object file
Turret/AdvancedMissileTurret.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/AdvancedMissileTurret.cpp.obj
.PHONY : Turret/AdvancedMissileTurret.cpp.obj

Turret/AdvancedMissileTurret.i: Turret/AdvancedMissileTurret.cpp.i
.PHONY : Turret/AdvancedMissileTurret.i

# target to preprocess a source file
Turret/AdvancedMissileTurret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/AdvancedMissileTurret.cpp.i
.PHONY : Turret/AdvancedMissileTurret.cpp.i

Turret/AdvancedMissileTurret.s: Turret/AdvancedMissileTurret.cpp.s
.PHONY : Turret/AdvancedMissileTurret.s

# target to generate assembly for a file
Turret/AdvancedMissileTurret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/AdvancedMissileTurret.cpp.s
.PHONY : Turret/AdvancedMissileTurret.cpp.s

Turret/BerserkPotion.obj: Turret/BerserkPotion.cpp.obj
.PHONY : Turret/BerserkPotion.obj

# target to build an object file
Turret/BerserkPotion.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/BerserkPotion.cpp.obj
.PHONY : Turret/BerserkPotion.cpp.obj

Turret/BerserkPotion.i: Turret/BerserkPotion.cpp.i
.PHONY : Turret/BerserkPotion.i

# target to preprocess a source file
Turret/BerserkPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/BerserkPotion.cpp.i
.PHONY : Turret/BerserkPotion.cpp.i

Turret/BerserkPotion.s: Turret/BerserkPotion.cpp.s
.PHONY : Turret/BerserkPotion.s

# target to generate assembly for a file
Turret/BerserkPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/BerserkPotion.cpp.s
.PHONY : Turret/BerserkPotion.cpp.s

Turret/ExplosionMine.obj: Turret/ExplosionMine.cpp.obj
.PHONY : Turret/ExplosionMine.obj

# target to build an object file
Turret/ExplosionMine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ExplosionMine.cpp.obj
.PHONY : Turret/ExplosionMine.cpp.obj

Turret/ExplosionMine.i: Turret/ExplosionMine.cpp.i
.PHONY : Turret/ExplosionMine.i

# target to preprocess a source file
Turret/ExplosionMine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ExplosionMine.cpp.i
.PHONY : Turret/ExplosionMine.cpp.i

Turret/ExplosionMine.s: Turret/ExplosionMine.cpp.s
.PHONY : Turret/ExplosionMine.s

# target to generate assembly for a file
Turret/ExplosionMine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ExplosionMine.cpp.s
.PHONY : Turret/ExplosionMine.cpp.s

Turret/FrostPotion.obj: Turret/FrostPotion.cpp.obj
.PHONY : Turret/FrostPotion.obj

# target to build an object file
Turret/FrostPotion.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/FrostPotion.cpp.obj
.PHONY : Turret/FrostPotion.cpp.obj

Turret/FrostPotion.i: Turret/FrostPotion.cpp.i
.PHONY : Turret/FrostPotion.i

# target to preprocess a source file
Turret/FrostPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/FrostPotion.cpp.i
.PHONY : Turret/FrostPotion.cpp.i

Turret/FrostPotion.s: Turret/FrostPotion.cpp.s
.PHONY : Turret/FrostPotion.s

# target to generate assembly for a file
Turret/FrostPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/FrostPotion.cpp.s
.PHONY : Turret/FrostPotion.cpp.s

Turret/HoverTurretButton.obj: Turret/HoverTurretButton.cpp.obj
.PHONY : Turret/HoverTurretButton.obj

# target to build an object file
Turret/HoverTurretButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/HoverTurretButton.cpp.obj
.PHONY : Turret/HoverTurretButton.cpp.obj

Turret/HoverTurretButton.i: Turret/HoverTurretButton.cpp.i
.PHONY : Turret/HoverTurretButton.i

# target to preprocess a source file
Turret/HoverTurretButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/HoverTurretButton.cpp.i
.PHONY : Turret/HoverTurretButton.cpp.i

Turret/HoverTurretButton.s: Turret/HoverTurretButton.cpp.s
.PHONY : Turret/HoverTurretButton.s

# target to generate assembly for a file
Turret/HoverTurretButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/HoverTurretButton.cpp.s
.PHONY : Turret/HoverTurretButton.cpp.s

Turret/LaserTurret.obj: Turret/LaserTurret.cpp.obj
.PHONY : Turret/LaserTurret.obj

# target to build an object file
Turret/LaserTurret.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/LaserTurret.cpp.obj
.PHONY : Turret/LaserTurret.cpp.obj

Turret/LaserTurret.i: Turret/LaserTurret.cpp.i
.PHONY : Turret/LaserTurret.i

# target to preprocess a source file
Turret/LaserTurret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/LaserTurret.cpp.i
.PHONY : Turret/LaserTurret.cpp.i

Turret/LaserTurret.s: Turret/LaserTurret.cpp.s
.PHONY : Turret/LaserTurret.s

# target to generate assembly for a file
Turret/LaserTurret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/LaserTurret.cpp.s
.PHONY : Turret/LaserTurret.cpp.s

Turret/MachineGunTurret.obj: Turret/MachineGunTurret.cpp.obj
.PHONY : Turret/MachineGunTurret.obj

# target to build an object file
Turret/MachineGunTurret.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MachineGunTurret.cpp.obj
.PHONY : Turret/MachineGunTurret.cpp.obj

Turret/MachineGunTurret.i: Turret/MachineGunTurret.cpp.i
.PHONY : Turret/MachineGunTurret.i

# target to preprocess a source file
Turret/MachineGunTurret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MachineGunTurret.cpp.i
.PHONY : Turret/MachineGunTurret.cpp.i

Turret/MachineGunTurret.s: Turret/MachineGunTurret.cpp.s
.PHONY : Turret/MachineGunTurret.s

# target to generate assembly for a file
Turret/MachineGunTurret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MachineGunTurret.cpp.s
.PHONY : Turret/MachineGunTurret.cpp.s

Turret/Mine.obj: Turret/Mine.cpp.obj
.PHONY : Turret/Mine.obj

# target to build an object file
Turret/Mine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Mine.cpp.obj
.PHONY : Turret/Mine.cpp.obj

Turret/Mine.i: Turret/Mine.cpp.i
.PHONY : Turret/Mine.i

# target to preprocess a source file
Turret/Mine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Mine.cpp.i
.PHONY : Turret/Mine.cpp.i

Turret/Mine.s: Turret/Mine.cpp.s
.PHONY : Turret/Mine.s

# target to generate assembly for a file
Turret/Mine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Mine.cpp.s
.PHONY : Turret/Mine.cpp.s

Turret/MissileTurret.obj: Turret/MissileTurret.cpp.obj
.PHONY : Turret/MissileTurret.obj

# target to build an object file
Turret/MissileTurret.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MissileTurret.cpp.obj
.PHONY : Turret/MissileTurret.cpp.obj

Turret/MissileTurret.i: Turret/MissileTurret.cpp.i
.PHONY : Turret/MissileTurret.i

# target to preprocess a source file
Turret/MissileTurret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MissileTurret.cpp.i
.PHONY : Turret/MissileTurret.cpp.i

Turret/MissileTurret.s: Turret/MissileTurret.cpp.s
.PHONY : Turret/MissileTurret.s

# target to generate assembly for a file
Turret/MissileTurret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/MissileTurret.cpp.s
.PHONY : Turret/MissileTurret.cpp.s

Turret/Potion.obj: Turret/Potion.cpp.obj
.PHONY : Turret/Potion.obj

# target to build an object file
Turret/Potion.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Potion.cpp.obj
.PHONY : Turret/Potion.cpp.obj

Turret/Potion.i: Turret/Potion.cpp.i
.PHONY : Turret/Potion.i

# target to preprocess a source file
Turret/Potion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Potion.cpp.i
.PHONY : Turret/Potion.cpp.i

Turret/Potion.s: Turret/Potion.cpp.s
.PHONY : Turret/Potion.s

# target to generate assembly for a file
Turret/Potion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Potion.cpp.s
.PHONY : Turret/Potion.cpp.s

Turret/ShieldPotion.obj: Turret/ShieldPotion.cpp.obj
.PHONY : Turret/ShieldPotion.obj

# target to build an object file
Turret/ShieldPotion.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ShieldPotion.cpp.obj
.PHONY : Turret/ShieldPotion.cpp.obj

Turret/ShieldPotion.i: Turret/ShieldPotion.cpp.i
.PHONY : Turret/ShieldPotion.i

# target to preprocess a source file
Turret/ShieldPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ShieldPotion.cpp.i
.PHONY : Turret/ShieldPotion.cpp.i

Turret/ShieldPotion.s: Turret/ShieldPotion.cpp.s
.PHONY : Turret/ShieldPotion.s

# target to generate assembly for a file
Turret/ShieldPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/ShieldPotion.cpp.s
.PHONY : Turret/ShieldPotion.cpp.s

Turret/Shovel.obj: Turret/Shovel.cpp.obj
.PHONY : Turret/Shovel.obj

# target to build an object file
Turret/Shovel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Shovel.cpp.obj
.PHONY : Turret/Shovel.cpp.obj

Turret/Shovel.i: Turret/Shovel.cpp.i
.PHONY : Turret/Shovel.i

# target to preprocess a source file
Turret/Shovel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Shovel.cpp.i
.PHONY : Turret/Shovel.cpp.i

Turret/Shovel.s: Turret/Shovel.cpp.s
.PHONY : Turret/Shovel.s

# target to generate assembly for a file
Turret/Shovel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Shovel.cpp.s
.PHONY : Turret/Shovel.cpp.s

Turret/TeleportMine.obj: Turret/TeleportMine.cpp.obj
.PHONY : Turret/TeleportMine.obj

# target to build an object file
Turret/TeleportMine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TeleportMine.cpp.obj
.PHONY : Turret/TeleportMine.cpp.obj

Turret/TeleportMine.i: Turret/TeleportMine.cpp.i
.PHONY : Turret/TeleportMine.i

# target to preprocess a source file
Turret/TeleportMine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TeleportMine.cpp.i
.PHONY : Turret/TeleportMine.cpp.i

Turret/TeleportMine.s: Turret/TeleportMine.cpp.s
.PHONY : Turret/TeleportMine.s

# target to generate assembly for a file
Turret/TeleportMine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TeleportMine.cpp.s
.PHONY : Turret/TeleportMine.cpp.s

Turret/Turret.obj: Turret/Turret.cpp.obj
.PHONY : Turret/Turret.obj

# target to build an object file
Turret/Turret.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Turret.cpp.obj
.PHONY : Turret/Turret.cpp.obj

Turret/Turret.i: Turret/Turret.cpp.i
.PHONY : Turret/Turret.i

# target to preprocess a source file
Turret/Turret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Turret.cpp.i
.PHONY : Turret/Turret.cpp.i

Turret/Turret.s: Turret/Turret.cpp.s
.PHONY : Turret/Turret.s

# target to generate assembly for a file
Turret/Turret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/Turret.cpp.s
.PHONY : Turret/Turret.cpp.s

Turret/TurretButton.obj: Turret/TurretButton.cpp.obj
.PHONY : Turret/TurretButton.obj

# target to build an object file
Turret/TurretButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TurretButton.cpp.obj
.PHONY : Turret/TurretButton.cpp.obj

Turret/TurretButton.i: Turret/TurretButton.cpp.i
.PHONY : Turret/TurretButton.i

# target to preprocess a source file
Turret/TurretButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TurretButton.cpp.i
.PHONY : Turret/TurretButton.cpp.i

Turret/TurretButton.s: Turret/TurretButton.cpp.s
.PHONY : Turret/TurretButton.s

# target to generate assembly for a file
Turret/TurretButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/Turret/TurretButton.cpp.s
.PHONY : Turret/TurretButton.cpp.s

UI/Animation/DirtyEffect.obj: UI/Animation/DirtyEffect.cpp.obj
.PHONY : UI/Animation/DirtyEffect.obj

# target to build an object file
UI/Animation/DirtyEffect.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/DirtyEffect.cpp.obj
.PHONY : UI/Animation/DirtyEffect.cpp.obj

UI/Animation/DirtyEffect.i: UI/Animation/DirtyEffect.cpp.i
.PHONY : UI/Animation/DirtyEffect.i

# target to preprocess a source file
UI/Animation/DirtyEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/DirtyEffect.cpp.i
.PHONY : UI/Animation/DirtyEffect.cpp.i

UI/Animation/DirtyEffect.s: UI/Animation/DirtyEffect.cpp.s
.PHONY : UI/Animation/DirtyEffect.s

# target to generate assembly for a file
UI/Animation/DirtyEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/DirtyEffect.cpp.s
.PHONY : UI/Animation/DirtyEffect.cpp.s

UI/Animation/ExplosionEffect.obj: UI/Animation/ExplosionEffect.cpp.obj
.PHONY : UI/Animation/ExplosionEffect.obj

# target to build an object file
UI/Animation/ExplosionEffect.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/ExplosionEffect.cpp.obj
.PHONY : UI/Animation/ExplosionEffect.cpp.obj

UI/Animation/ExplosionEffect.i: UI/Animation/ExplosionEffect.cpp.i
.PHONY : UI/Animation/ExplosionEffect.i

# target to preprocess a source file
UI/Animation/ExplosionEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/ExplosionEffect.cpp.i
.PHONY : UI/Animation/ExplosionEffect.cpp.i

UI/Animation/ExplosionEffect.s: UI/Animation/ExplosionEffect.cpp.s
.PHONY : UI/Animation/ExplosionEffect.s

# target to generate assembly for a file
UI/Animation/ExplosionEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/ExplosionEffect.cpp.s
.PHONY : UI/Animation/ExplosionEffect.cpp.s

UI/Animation/Plane.obj: UI/Animation/Plane.cpp.obj
.PHONY : UI/Animation/Plane.obj

# target to build an object file
UI/Animation/Plane.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/Plane.cpp.obj
.PHONY : UI/Animation/Plane.cpp.obj

UI/Animation/Plane.i: UI/Animation/Plane.cpp.i
.PHONY : UI/Animation/Plane.i

# target to preprocess a source file
UI/Animation/Plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/Plane.cpp.i
.PHONY : UI/Animation/Plane.cpp.i

UI/Animation/Plane.s: UI/Animation/Plane.cpp.s
.PHONY : UI/Animation/Plane.s

# target to generate assembly for a file
UI/Animation/Plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Animation/Plane.cpp.s
.PHONY : UI/Animation/Plane.cpp.s

UI/Component/DrawBoard.obj: UI/Component/DrawBoard.cpp.obj
.PHONY : UI/Component/DrawBoard.obj

# target to build an object file
UI/Component/DrawBoard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/DrawBoard.cpp.obj
.PHONY : UI/Component/DrawBoard.cpp.obj

UI/Component/DrawBoard.i: UI/Component/DrawBoard.cpp.i
.PHONY : UI/Component/DrawBoard.i

# target to preprocess a source file
UI/Component/DrawBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/DrawBoard.cpp.i
.PHONY : UI/Component/DrawBoard.cpp.i

UI/Component/DrawBoard.s: UI/Component/DrawBoard.cpp.s
.PHONY : UI/Component/DrawBoard.s

# target to generate assembly for a file
UI/Component/DrawBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/DrawBoard.cpp.s
.PHONY : UI/Component/DrawBoard.cpp.s

UI/Component/EnemyButton.obj: UI/Component/EnemyButton.cpp.obj
.PHONY : UI/Component/EnemyButton.obj

# target to build an object file
UI/Component/EnemyButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/EnemyButton.cpp.obj
.PHONY : UI/Component/EnemyButton.cpp.obj

UI/Component/EnemyButton.i: UI/Component/EnemyButton.cpp.i
.PHONY : UI/Component/EnemyButton.i

# target to preprocess a source file
UI/Component/EnemyButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/EnemyButton.cpp.i
.PHONY : UI/Component/EnemyButton.cpp.i

UI/Component/EnemyButton.s: UI/Component/EnemyButton.cpp.s
.PHONY : UI/Component/EnemyButton.s

# target to generate assembly for a file
UI/Component/EnemyButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/EnemyButton.cpp.s
.PHONY : UI/Component/EnemyButton.cpp.s

UI/Component/HoverImageButton.obj: UI/Component/HoverImageButton.cpp.obj
.PHONY : UI/Component/HoverImageButton.obj

# target to build an object file
UI/Component/HoverImageButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/HoverImageButton.cpp.obj
.PHONY : UI/Component/HoverImageButton.cpp.obj

UI/Component/HoverImageButton.i: UI/Component/HoverImageButton.cpp.i
.PHONY : UI/Component/HoverImageButton.i

# target to preprocess a source file
UI/Component/HoverImageButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/HoverImageButton.cpp.i
.PHONY : UI/Component/HoverImageButton.cpp.i

UI/Component/HoverImageButton.s: UI/Component/HoverImageButton.cpp.s
.PHONY : UI/Component/HoverImageButton.s

# target to generate assembly for a file
UI/Component/HoverImageButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/HoverImageButton.cpp.s
.PHONY : UI/Component/HoverImageButton.cpp.s

UI/Component/Image.obj: UI/Component/Image.cpp.obj
.PHONY : UI/Component/Image.obj

# target to build an object file
UI/Component/Image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Image.cpp.obj
.PHONY : UI/Component/Image.cpp.obj

UI/Component/Image.i: UI/Component/Image.cpp.i
.PHONY : UI/Component/Image.i

# target to preprocess a source file
UI/Component/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Image.cpp.i
.PHONY : UI/Component/Image.cpp.i

UI/Component/Image.s: UI/Component/Image.cpp.s
.PHONY : UI/Component/Image.s

# target to generate assembly for a file
UI/Component/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Image.cpp.s
.PHONY : UI/Component/Image.cpp.s

UI/Component/ImageButton.obj: UI/Component/ImageButton.cpp.obj
.PHONY : UI/Component/ImageButton.obj

# target to build an object file
UI/Component/ImageButton.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/ImageButton.cpp.obj
.PHONY : UI/Component/ImageButton.cpp.obj

UI/Component/ImageButton.i: UI/Component/ImageButton.cpp.i
.PHONY : UI/Component/ImageButton.i

# target to preprocess a source file
UI/Component/ImageButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/ImageButton.cpp.i
.PHONY : UI/Component/ImageButton.cpp.i

UI/Component/ImageButton.s: UI/Component/ImageButton.cpp.s
.PHONY : UI/Component/ImageButton.s

# target to generate assembly for a file
UI/Component/ImageButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/ImageButton.cpp.s
.PHONY : UI/Component/ImageButton.cpp.s

UI/Component/Label.obj: UI/Component/Label.cpp.obj
.PHONY : UI/Component/Label.obj

# target to build an object file
UI/Component/Label.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Label.cpp.obj
.PHONY : UI/Component/Label.cpp.obj

UI/Component/Label.i: UI/Component/Label.cpp.i
.PHONY : UI/Component/Label.i

# target to preprocess a source file
UI/Component/Label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Label.cpp.i
.PHONY : UI/Component/Label.cpp.i

UI/Component/Label.s: UI/Component/Label.cpp.s
.PHONY : UI/Component/Label.s

# target to generate assembly for a file
UI/Component/Label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Label.cpp.s
.PHONY : UI/Component/Label.cpp.s

UI/Component/Slider.obj: UI/Component/Slider.cpp.obj
.PHONY : UI/Component/Slider.obj

# target to build an object file
UI/Component/Slider.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Slider.cpp.obj
.PHONY : UI/Component/Slider.cpp.obj

UI/Component/Slider.i: UI/Component/Slider.cpp.i
.PHONY : UI/Component/Slider.i

# target to preprocess a source file
UI/Component/Slider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Slider.cpp.i
.PHONY : UI/Component/Slider.cpp.i

UI/Component/Slider.s: UI/Component/Slider.cpp.s
.PHONY : UI/Component/Slider.s

# target to generate assembly for a file
UI/Component/Slider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/Slider.cpp.s
.PHONY : UI/Component/Slider.cpp.s

UI/Component/TextInput.obj: UI/Component/TextInput.cpp.obj
.PHONY : UI/Component/TextInput.obj

# target to build an object file
UI/Component/TextInput.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/TextInput.cpp.obj
.PHONY : UI/Component/TextInput.cpp.obj

UI/Component/TextInput.i: UI/Component/TextInput.cpp.i
.PHONY : UI/Component/TextInput.i

# target to preprocess a source file
UI/Component/TextInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/TextInput.cpp.i
.PHONY : UI/Component/TextInput.cpp.i

UI/Component/TextInput.s: UI/Component/TextInput.cpp.s
.PHONY : UI/Component/TextInput.s

# target to generate assembly for a file
UI/Component/TextInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/UI/Component/TextInput.cpp.s
.PHONY : UI/Component/TextInput.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\2024_I2P2_TowerDefense_with_answer.dir\build.make CMakeFiles/2024_I2P2_TowerDefense_with_answer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... 2024_I2P2_TowerDefense_with_answer
	@echo ... Bullet/AdvancedMissileBullet.obj
	@echo ... Bullet/AdvancedMissileBullet.i
	@echo ... Bullet/AdvancedMissileBullet.s
	@echo ... Bullet/Bullet.obj
	@echo ... Bullet/Bullet.i
	@echo ... Bullet/Bullet.s
	@echo ... Bullet/FireBullet.obj
	@echo ... Bullet/FireBullet.i
	@echo ... Bullet/FireBullet.s
	@echo ... Bullet/FrostBullet.obj
	@echo ... Bullet/FrostBullet.i
	@echo ... Bullet/FrostBullet.s
	@echo ... Bullet/LaserBullet.obj
	@echo ... Bullet/LaserBullet.i
	@echo ... Bullet/LaserBullet.s
	@echo ... Bullet/MissileBullet.obj
	@echo ... Bullet/MissileBullet.i
	@echo ... Bullet/MissileBullet.s
	@echo ... Enemy/AdvancedTankEnemy.obj
	@echo ... Enemy/AdvancedTankEnemy.i
	@echo ... Enemy/AdvancedTankEnemy.s
	@echo ... Enemy/Enemy.obj
	@echo ... Enemy/Enemy.i
	@echo ... Enemy/Enemy.s
	@echo ... Enemy/PlaneEnemy.obj
	@echo ... Enemy/PlaneEnemy.i
	@echo ... Enemy/PlaneEnemy.s
	@echo ... Enemy/SoldierEnemy.obj
	@echo ... Enemy/SoldierEnemy.i
	@echo ... Enemy/SoldierEnemy.s
	@echo ... Enemy/TankEnemy.obj
	@echo ... Enemy/TankEnemy.i
	@echo ... Enemy/TankEnemy.s
	@echo ... Engine/Allegro5Exception.obj
	@echo ... Engine/Allegro5Exception.i
	@echo ... Engine/Allegro5Exception.s
	@echo ... Engine/AudioHelper.obj
	@echo ... Engine/AudioHelper.i
	@echo ... Engine/AudioHelper.s
	@echo ... Engine/Collider.obj
	@echo ... Engine/Collider.i
	@echo ... Engine/Collider.s
	@echo ... Engine/GameEngine.obj
	@echo ... Engine/GameEngine.i
	@echo ... Engine/GameEngine.s
	@echo ... Engine/Group.obj
	@echo ... Engine/Group.i
	@echo ... Engine/Group.s
	@echo ... Engine/IControl.obj
	@echo ... Engine/IControl.i
	@echo ... Engine/IControl.s
	@echo ... Engine/IObject.obj
	@echo ... Engine/IObject.i
	@echo ... Engine/IObject.s
	@echo ... Engine/IScene.obj
	@echo ... Engine/IScene.i
	@echo ... Engine/IScene.s
	@echo ... Engine/LOG.obj
	@echo ... Engine/LOG.i
	@echo ... Engine/LOG.s
	@echo ... Engine/Point.obj
	@echo ... Engine/Point.i
	@echo ... Engine/Point.s
	@echo ... Engine/Resources.obj
	@echo ... Engine/Resources.i
	@echo ... Engine/Resources.s
	@echo ... Engine/Sprite.obj
	@echo ... Engine/Sprite.i
	@echo ... Engine/Sprite.s
	@echo ... Scene/BlackPlayScene.obj
	@echo ... Scene/BlackPlayScene.i
	@echo ... Scene/BlackPlayScene.s
	@echo ... Scene/DataGeneratingScene.obj
	@echo ... Scene/DataGeneratingScene.i
	@echo ... Scene/DataGeneratingScene.s
	@echo ... Scene/DifficultySelectScene.obj
	@echo ... Scene/DifficultySelectScene.i
	@echo ... Scene/DifficultySelectScene.s
	@echo ... Scene/LoseScene.obj
	@echo ... Scene/LoseScene.i
	@echo ... Scene/LoseScene.s
	@echo ... Scene/MapCreateScene.obj
	@echo ... Scene/MapCreateScene.i
	@echo ... Scene/MapCreateScene.s
	@echo ... Scene/ModeSelectScene.obj
	@echo ... Scene/ModeSelectScene.i
	@echo ... Scene/ModeSelectScene.s
	@echo ... Scene/NormalPlayScene.obj
	@echo ... Scene/NormalPlayScene.i
	@echo ... Scene/NormalPlayScene.s
	@echo ... Scene/PlayScene.obj
	@echo ... Scene/PlayScene.i
	@echo ... Scene/PlayScene.s
	@echo ... Scene/ReversePlayScene.obj
	@echo ... Scene/ReversePlayScene.i
	@echo ... Scene/ReversePlayScene.s
	@echo ... Scene/ReviveScene.obj
	@echo ... Scene/ReviveScene.i
	@echo ... Scene/ReviveScene.s
	@echo ... Scene/ScoreboardScene.obj
	@echo ... Scene/ScoreboardScene.i
	@echo ... Scene/ScoreboardScene.s
	@echo ... Scene/SettingsScene.obj
	@echo ... Scene/SettingsScene.i
	@echo ... Scene/SettingsScene.s
	@echo ... Scene/StageSelectHandWriteScene.obj
	@echo ... Scene/StageSelectHandWriteScene.i
	@echo ... Scene/StageSelectHandWriteScene.s
	@echo ... Scene/StageSelectScene.obj
	@echo ... Scene/StageSelectScene.i
	@echo ... Scene/StageSelectScene.s
	@echo ... Scene/StartScene.obj
	@echo ... Scene/StartScene.i
	@echo ... Scene/StartScene.s
	@echo ... Scene/SurvivalPlayScene.obj
	@echo ... Scene/SurvivalPlayScene.i
	@echo ... Scene/SurvivalPlayScene.s
	@echo ... Scene/WinScene.obj
	@echo ... Scene/WinScene.i
	@echo ... Scene/WinScene.s
	@echo ... Turret/AdvancedMissileTurret.obj
	@echo ... Turret/AdvancedMissileTurret.i
	@echo ... Turret/AdvancedMissileTurret.s
	@echo ... Turret/BerserkPotion.obj
	@echo ... Turret/BerserkPotion.i
	@echo ... Turret/BerserkPotion.s
	@echo ... Turret/ExplosionMine.obj
	@echo ... Turret/ExplosionMine.i
	@echo ... Turret/ExplosionMine.s
	@echo ... Turret/FrostPotion.obj
	@echo ... Turret/FrostPotion.i
	@echo ... Turret/FrostPotion.s
	@echo ... Turret/HoverTurretButton.obj
	@echo ... Turret/HoverTurretButton.i
	@echo ... Turret/HoverTurretButton.s
	@echo ... Turret/LaserTurret.obj
	@echo ... Turret/LaserTurret.i
	@echo ... Turret/LaserTurret.s
	@echo ... Turret/MachineGunTurret.obj
	@echo ... Turret/MachineGunTurret.i
	@echo ... Turret/MachineGunTurret.s
	@echo ... Turret/Mine.obj
	@echo ... Turret/Mine.i
	@echo ... Turret/Mine.s
	@echo ... Turret/MissileTurret.obj
	@echo ... Turret/MissileTurret.i
	@echo ... Turret/MissileTurret.s
	@echo ... Turret/Potion.obj
	@echo ... Turret/Potion.i
	@echo ... Turret/Potion.s
	@echo ... Turret/ShieldPotion.obj
	@echo ... Turret/ShieldPotion.i
	@echo ... Turret/ShieldPotion.s
	@echo ... Turret/Shovel.obj
	@echo ... Turret/Shovel.i
	@echo ... Turret/Shovel.s
	@echo ... Turret/TeleportMine.obj
	@echo ... Turret/TeleportMine.i
	@echo ... Turret/TeleportMine.s
	@echo ... Turret/Turret.obj
	@echo ... Turret/Turret.i
	@echo ... Turret/Turret.s
	@echo ... Turret/TurretButton.obj
	@echo ... Turret/TurretButton.i
	@echo ... Turret/TurretButton.s
	@echo ... UI/Animation/DirtyEffect.obj
	@echo ... UI/Animation/DirtyEffect.i
	@echo ... UI/Animation/DirtyEffect.s
	@echo ... UI/Animation/ExplosionEffect.obj
	@echo ... UI/Animation/ExplosionEffect.i
	@echo ... UI/Animation/ExplosionEffect.s
	@echo ... UI/Animation/Plane.obj
	@echo ... UI/Animation/Plane.i
	@echo ... UI/Animation/Plane.s
	@echo ... UI/Component/DrawBoard.obj
	@echo ... UI/Component/DrawBoard.i
	@echo ... UI/Component/DrawBoard.s
	@echo ... UI/Component/EnemyButton.obj
	@echo ... UI/Component/EnemyButton.i
	@echo ... UI/Component/EnemyButton.s
	@echo ... UI/Component/HoverImageButton.obj
	@echo ... UI/Component/HoverImageButton.i
	@echo ... UI/Component/HoverImageButton.s
	@echo ... UI/Component/Image.obj
	@echo ... UI/Component/Image.i
	@echo ... UI/Component/Image.s
	@echo ... UI/Component/ImageButton.obj
	@echo ... UI/Component/ImageButton.i
	@echo ... UI/Component/ImageButton.s
	@echo ... UI/Component/Label.obj
	@echo ... UI/Component/Label.i
	@echo ... UI/Component/Label.s
	@echo ... UI/Component/Slider.obj
	@echo ... UI/Component/Slider.i
	@echo ... UI/Component/Slider.s
	@echo ... UI/Component/TextInput.obj
	@echo ... UI/Component/TextInput.i
	@echo ... UI/Component/TextInput.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

